var translations = {
    //todo: finish this
    "REFINED_DIAMOND": "Refined Diamond",
    "REFINED_MITHRIL": "Refined Mithril",
    "REFINED_TITANIUM": "Refined Titanium",
    "FUEL_TANK": "Fuel Tank",
    "BEJEWELED_HANDLE": "Bejeweled Handle",
    "BEJEWELED_COLLAR": "Bejeweled Collar",
    "DRILL_ENGINE": "Drill Engine",
    "GOLDEN_PLATE": "Golden Plate",
    "MITHRIL_PLATE": "Mithril Plate",
    "GEMSTONE_MIXTURE": "Gemstone Mixture",
    "PERFECT_JASPER_GEM": "Perfect Jasper Gem",
    "PERFECT_RUBY_GEM": "Perfect Ruby Gem",
    "PERFECT_JADE_GEM": "Perfect Jade Gem",
    "PERFECT_SAPPHIRE_GEM": "Perfect Sapphire Gem",
    "PERFECT_AMBER_GEM": "Perfect Amber Gem",
    "PERFECT_TOPAZ_GEM": "Perfect Topaz Gem",
    "PERFECT_AMETHYST_GEM": "Perfect Amethyst Gem",
    "PERFECT_OPAL_GEM": "Perfect Opal Gem",
    "PERFECT_ONYX_GEM": "Perfect Onyx Gem",
    "PERFECT_CITRINE_GEM": "Perfect Citrine Gem",
    "PERFECT_AQUAMARINE_GEM": "Perfect Aquamarine Gem",
    "PERFECT_PERIDOT_GEM": "Perfect Peridot Gem",
    //HOTM2
    "MITHRIL_PICKAXE": "Mithril Pickaxe",
    "BEACON_2": "Beacon II",
    "TITANIUM_TALISMAN": "Titanium Talisman",
    "DIAMONITE": "Diamonite",
    "POWER_CRYSTAL": "Power Crystal",
    "FORGE_TRAVEL_SCROLL": "Forge Scroll",
    //HOTM3
    "REFINED_MITHRIL_PICKAXE": "Refined Mithril Pickaxe",
    "MITHRIL_DRILL_1": "Mithril Drill SX-R226",
    "MITHRIL_FUEL_TANK": "Mithril Fuel Tank",
    "MITHRIL_DRILL_ENGINE": "Mithril Drill Engine",
    "BEACON_3": "Beacon III",
    "TITANIUM_RING": "Titanium Ring",
    "PURE_MITHRIL": "Pure Mithril",
    "ROCK_GEMSTONE": "Rock Gemstone",
    "PETRIFIED_STARFALL": "Petrified Starfall",
    "GEMSTONE_DRILL_1": "Ruby Drill TX-15",
    //HOTM4
    "GOBLIN_OMELETTE_PESTO": "Pesto Goblin Omelette",
    "PET": "Ammonite Pet",
    "MITHRIL_DRILL_2": "Mithril Drill SX-R326",
    "TITANIUM_DRILL_ENGINE": "Titanium Drill Engine",
    "GOBLIN_OMELETTE": "Goblin Omelette",
    "BEACON_4": "Beacon IV",
    "TITANIUM_ARTIFACT": "Titanium Artifact",
    "HOT_STUFF": "Hot Stuff",
    "GEMSTONE_DRILL_2": "Gemstone Drill LT-522",
    //HOTM5
    "TITANIUM_DRILL_1": "Titanium Drill DR-X355",
    "TITANIUM_DRILL_2": "Titanium Drill DR-X455",
    "TITANIUM_DRILL_3": "Titanium Drill DR-X555",
    "TITANIUM_FUEL_TANK": "Titanium Fuel Tank",
    "BEACON_5": "Beacon V",
    "TITANIUM_RELIC": "Titanium Relic",
    "GOBLIN_OMELETTE_SPICY": "Spicy Goblin Omelette",
    "GEMSTONE_CHAMBER": "Gemstone Chamber",
    "GEMSTONE_DRILL_3": "Topaz Drill KGR-12",
    "RUBY_POLISHED_DRILL_ENGINE": "Ruby Drill Engine",
    "GEMSTONE_FUEL_TANK": "Gemstone Fuel Tank",
    //HOTM6
    "GOBLIN_OMELETTE_SUNNY_SIDE": "Sunny Side Goblin Omelette",
    "GOBLIN_OMELETTE_BLUE_CHEESE": "Blue Cheese Goblin Omelette",
    "TITANIUM_DRILL_4": "Titanium Drill DR-X655",
    "GEMSTONE_DRILL_4": "Jasper Drill X",
    "SAPPHIRE_POLISHED_DRILL_ENGINE": "Sapphire Drill Engine",
    "AMBER_MATERIAL": "Amber Material",
    "DIVAN_HELMET": "Helmet of Divan",
    "DIVAN_CHESTPLATE": "Chestplate of Divan",
    "DIVAN_LEGGINGS": "Leggings of Divan",
    "DIVAN_BOOTS": "Boots of Divan",
    //HOTM7
    "AMBER_POLISHED_DRILL_ENGINE": "Amber Drill Engine",
    "PERFECTLY_CUT_FUEL_TANK": "Perfectly-Cut Fuel Tank",
    "DIVAN_DRILL": "Divan's Drill",
  }
  var times = {
    "REFINED_DIAMOND": 28800,
    "REFINED_MITHRIL": 21600,
    "REFINED_TITANIUM": 43200,
    "FUEL_TANK": 36000,
    "BEJEWELED_HANDLE": 1800,
    "BEJEWELED_COLLAR": 7200,
    "DRILL_ENGINE": 108000,
    "GOLDEN_PLATE": 21600,
    "MITHRIL_PLATE": 64800,
    "GEMSTONE_MIXTURE": 14400,
    "PERFECT_JASPER_GEM": 72000,
    "PERFECT_RUBY_GEM": 72000,
    "PERFECT_JADE_GEM": 72000,
    "PERFECT_SAPPHIRE_GEM": 72000,
    "PERFECT_AMBER_GEM": 72000,
    "PERFECT_TOPAZ_GEM": 72000,
    "PERFECT_AMETHYST_GEM": 72000,
    "PERFECT_OPAL_GEM": 72000,
    "PERFECT_ONYX_GEM": 72000,
    "PERFECT_CITRINE_GEM": 72000,
    "PERFECT_AQUAMARINE_GEM": 72000,
    "PERFECT_PERIDOT_GEM": 72000,
    //Casting 
    //HOTM2
    "MITHRIL_PICKAXE": 2700,
    "BEACON_2": 72000,
    "TITANIUM_TALISMAN": 50400,
    "DIAMONITE": 21600,
    "POWER_CRYSTAL": 7200,
    "FORGE_TRAVEL_SCROLL": 18000,
    //HOTM3
    "REFINED_MITHRIL_PICKAXE": 79200,
    "MITHRIL_DRILL_1": 14400,
    "MITHRIL_FUEL_TANK": 36000,
    "MITHRIL_DRILL_ENGINE": 54000,
    "BEACON_3": 108000,
    "TITANIUM_RING": 72000,
    "PURE_MITHRIL": 43200,
    "ROCK_GEMSTONE": 79200,
    "PETRIFIED_STARFALL": 50400,
    "GEMSTONE_DRILL_1": 3600,
    //HOTM4
    "GOBLIN_OMELETTE_PESTO": 72000,
    "PET": 1036800,
    "MITHRIL_DRILL_2": 30,
    "TITANIUM_DRILL_ENGINE": 108000,
    "GOBLIN_OMELETTE": 64800,
    "BEACON_4": 144000,
    "TITANIUM_ARTIFACT": 129600,
    "HOT_STUFF": 86400,
    "GEMSTONE_DRILL_2": 30,
    //HOTM5
    "TITANIUM_DRILL_1": 230400,
    "TITANIUM_DRILL_2": 30,
    "TITANIUM_DRILL_3": 30,
    "TITANIUM_FUEL_TANK": 90000,
    "BEACON_5": 180000,
    "TITANIUM_RELIC": 259200,
    "GOBLIN_OMELETTE_SPICY": 72000,
    "GEMSTONE_CHAMBER": 14400,
    "GEMSTONE_DRILL_3": 30,
    "RUBY_POLISHED_DRILL_ENGINE": 72000,
    "GEMSTONE_FUEL_TANK": 108000,
    //HOTM6
    "GOBLIN_OMELETTE_SUNNY_SIDE": 72000,
    "GOBLIN_OMELETTE_BLUE_CHEESE": 72000,
    "TITANIUM_DRILL_4": 30,
    "GEMSTONE_DRILL_4": 30,
    "SAPPHIRE_POLISHED_DRILL_ENGINE": 72000,
    "AMBER_MATERIAL": 25200,
    "DIVAN_HELMET": 82800,
    "DIVAN_CHESTPLATE": 82800,
    "DIVAN_LEGGINGS": 82800,
    "DIVAN_BOOTS": 82800,
    //HOTM7
    "AMBER_POLISHED_DRILL_ENGINE": 180000,
    "PERFECTLY_CUT_FUEL_TANK": 180000,
    "DIVAN_DRILL": 216000,
  }
  var quickforgetimes = {
    0: 1,
    1: 0.895,
    2: 0.89,
    3: 0.885,
    4: 0.88,
    5: 0.875,
    6: 0.87,
    7: 0.865,
    8: 0.86,
    9: 0.855,
    10: 0.85,
    11: 0.845,
    12: 0.84,
    13: 0.835,
    14: 0.83,
    15: 0.825,
    16: 0.82,
    17: 0.815,
    18: 0.81,
    19: 0.805,
    //WHY DOES IT WORK LIKE THIS????? I DON'T FUCKING KNOW
    20: 0.7,
  }
  var months = ["Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."];
  function fixTime(unit){
    if (unit < 10){
        return "0" + unit;
    }
    return unit;
  }