var translations = {
    //todo: finish this
    "REFINED_DIAMOND": "Refined Diamond",
    "REFINED_MITHRIL": "Refined Mithril",
    "REFINED_TITANIUM": "Refined Titanium",
    "FUEL_TANK": "Fuel Tank",
    "BEJEWELED_HANDLE": "Bejeweled Handle",
    "BEJEWELED_COLLAR": "Bejeweled Collar",
    "DRILL_ENGINE": "Drill Engine",
    "GOLDEN_PLATE": "Golden Plate",
    "MITHRIL_PLATE": "Mithril Plate",
    "GEMSTONE_MIXTURE": "Gemstone Mixture",
    "PERFECT_JASPER_GEM": "Perfect Jasper Gem",
    "PERFECT_RUBY_GEM": "Perfect Ruby Gem",
    "PERFECT_JADE_GEM": "Perfect Jade Gem",
    "PERFECT_SAPPHIRE_GEM": "Perfect Sapphire Gem",
    "PERFECT_AMBER_GEM": "Perfect Amber Gem",
    "PERFECT_TOPAZ_GEM": "Perfect Topaz Gem",
    "PERFECT_AMETHYST_GEM": "Perfect Amethyst Gem",
    "PERFECT_OPAL_GEM": "Perfect Opal Gem",
    "PERFECT_ONYX_GEM": "Perfect Onyx Gem",
    "PERFECT_CITRINE_GEM": "Perfect Citrine Gem",
    "PERFECT_AQUAMARINE_GEM": "Perfect Aquamarine Gem",
    "PERFECT_PERIDOT_GEM": "Perfect Peridot Gem",
    //HOTM2
    "MITHRIL_PICKAXE": "Mithril Pickaxe",
    "BEACON_2": "Beacon II",
    "TITANIUM_TALISMAN": "Titanium Talisman",
    "DIAMONITE": "Diamonite",
    "POWER_CRYSTAL": "Power Crystal",
    "FORGE_TRAVEL_SCROLL": "Forge Scroll",
    //HOTM3
    "REFINED_MITHRIL_PICKAXE": "Refined Mithril Pickaxe",
    "MITHRIL_DRILL_1": "Mithril Drill SX-R226",
    "MITHRIL_FUEL_TANK": "Mithril Fuel Tank",
    "MITHRIL_DRILL_ENGINE": "Mithril Drill Engine",
    "BEACON_3": "Beacon III",
    "TITANIUM_RING": "Titanium Ring",
    "PURE_MITHRIL": "Pure Mithril",
    "ROCK_GEMSTONE": "Rock Gemstone",
    "PETRIFIED_STARFALL": "Petrified Starfall",
    "GEMSTONE_DRILL_1": "Ruby Drill TX-15",
    //HOTM4
    "GOBLIN_OMELETTE_PESTO": "Pesto Goblin Omelette",
    "PET": "Ammonite Pet",
    "MITHRIL_DRILL_2": "Mithril Drill SX-R326",
    "TITANIUM_DRILL_ENGINE": "Titanium Drill Engine",
    "GOBLIN_OMELETTE": "Goblin Omelette",
    "BEACON_4": "Beacon IV",
    "TITANIUM_ARTIFACT": "Titanium Artifact",
    "HOT_STUFF": "Hot Stuff",
    "GEMSTONE_DRILL_2": "Gemstone Drill LT-522",
    //HOTM5
    "TITANIUM_DRILL_1": "Titanium Drill DR-X355",
    "TITANIUM_DRILL_2": "Titanium Drill DR-X455",
    "TITANIUM_DRILL_3": "Titanium Drill DR-X555",
    "TITANIUM_FUEL_TANK": "Titanium Fuel Tank",
    "BEACON_5": "Beacon V",
    "TITANIUM_RELIC": "Titanium Relic",
    "GOBLIN_OMELETTE_SPICY": "Spicy Goblin Omelette",
    "GEMSTONE_CHAMBER": "Gemstone Chamber",
    "GEMSTONE_DRILL_3": "Topaz Drill KGR-12",
    "RUBY_POLISHED_DRILL_ENGINE": "Ruby Drill Engine",
    "GEMSTONE_FUEL_TANK": "Gemstone Fuel Tank",
    //HOTM6
    "GOBLIN_OMELETTE_SUNNY_SIDE": "Sunny Side Goblin Omelette",
    "GOBLIN_OMELETTE_BLUE_CHEESE": "Blue Cheese Goblin Omelette",
    "TITANIUM_DRILL_4": "Titanium Drill DR-X655",
    "GEMSTONE_DRILL_4": "Jasper Drill X",
    "SAPPHIRE_POLISHED_DRILL_ENGINE": "Sapphire Drill Engine",
    "AMBER_MATERIAL": "Amber Material",
    "DIVAN_HELMET": "Helmet of Divan",
    "DIVAN_CHESTPLATE": "Chestplate of Divan",
    "DIVAN_LEGGINGS": "Leggings of Divan",
    "DIVAN_BOOTS": "Boots of Divan",
    //HOTM7
    "AMBER_POLISHED_DRILL_ENGINE": "Amber Drill Engine",
    "PERFECTLY_CUT_FUEL_TANK": "Perfectly-Cut Fuel Tank",
    "DIVAN_DRILL": "Divan's Drill",
    "BASE_CAMP_TRAVEL_SCROLL": "Base Camp Travel Scroll",
    "SECRET_RAILROAD_PASS": "Secret Railroad Pass",
    //Other
    "GLACITE_AMALGAMATION": "Glacite Amalgamation",
    "REFINED_UMBER": "Refined Umber",
    "REFINED_TUNGSTEN": "Refined Tungsten",
    "UMBER_PLATE": "Umber Plate",
    "TUNGSTEN_PLATE": "Tungsten Plate",
    "UMBER_KEY": "Umber Key",
    "TUNGSTEN_KEY": "Tungsten Key",
    "PERFECT_PLATE": "Perfect Plate",
    "FRIGID_HUSK": "Frigid Husk",
    "MOLE": "Mole Pet",
    "TYRANNOSAURUS": "T-Rex Pet",
    "SPINOSAURUS": "Spinosaurus Pet",
    "GOBLIN": "Goblin Pet",
    "ANKYLOSAURUS": "Ankylosaurus Pet",
    "PENGUIN": "Penguin Pet",
    "MAMMOTH": "Mammoth Pet",
    "DWARVEN_HANDWARMERS": "Dwarven Handwarmers",
    "REINFORCED_CHISEL": "Reinforced Chisel",
    "DWARVEN_METAL": "Dwarven Metal Talisman",
    "PORTABLE_CAMPFIRE": "Portable Campfire",
    "TUNGSTEN_KEYCHAIN": "Tungsten Keychain",
    "GLACITE_CHISEL": "Glacite Chisel",
    "PERFECT_CHISEL": "Perfect Chisel",
    "DIVAN_PENDANT": "Pendant of Divan",
    "POWER_RELIC": "Relic of Power",
    "SKELETON_KEY": "Skeleton Key",
  }
  var times = {
    "REFINED_DIAMOND": 28800,
    "REFINED_MITHRIL": 21600,
    "REFINED_TITANIUM": 43200,
    "FUEL_TANK": 36000,
    "BEJEWELED_HANDLE": 30,
    "BEJEWELED_COLLAR": 7200,
    "DRILL_ENGINE": 108000,
    "GOLDEN_PLATE": 21600,
    "MITHRIL_PLATE": 64800,
    "GEMSTONE_MIXTURE": 14400,
    "PERFECT_JASPER_GEM": 72000,
    "PERFECT_RUBY_GEM": 72000,
    "PERFECT_JADE_GEM": 72000,
    "PERFECT_SAPPHIRE_GEM": 72000,
    "PERFECT_AMBER_GEM": 72000,
    "PERFECT_TOPAZ_GEM": 72000,
    "PERFECT_AMETHYST_GEM": 72000,
    "PERFECT_OPAL_GEM": 72000,
    "PERFECT_ONYX_GEM": 72000,
    "PERFECT_CITRINE_GEM": 72000,
    "PERFECT_AQUAMARINE_GEM": 72000,
    "PERFECT_PERIDOT_GEM": 72000,
    //Casting 
    //HOTM2
    "MITHRIL_PICKAXE": 2700,
    "BEACON_2": 72000,
    "TITANIUM_TALISMAN": 50400,
    "DIAMONITE": 21600,
    "POWER_CRYSTAL": 7200,
    "FORGE_TRAVEL_SCROLL": 18000,
    //HOTM3
    "REFINED_MITHRIL_PICKAXE": 79200,
    "MITHRIL_DRILL_1": 14400,
    "MITHRIL_FUEL_TANK": 36000,
    "MITHRIL_DRILL_ENGINE": 54000,
    "BEACON_3": 108000,
    "TITANIUM_RING": 72000,
    "PURE_MITHRIL": 43200,
    "ROCK_GEMSTONE": 79200,
    "PETRIFIED_STARFALL": 50400,
    "GEMSTONE_DRILL_1": 3600,
    //HOTM4
    "GOBLIN_OMELETTE_PESTO": 72000,
    "PET": 1036800,
    "MITHRIL_DRILL_2": 30,
    "TITANIUM_DRILL_ENGINE": 108000,
    "GOBLIN_OMELETTE": 64800,
    "BEACON_4": 144000,
    "TITANIUM_ARTIFACT": 129600,
    "HOT_STUFF": 86400,
    "GEMSTONE_DRILL_2": 30,
    //HOTM5
    "TITANIUM_DRILL_1": 230400,
    "TITANIUM_DRILL_2": 30,
    "TITANIUM_DRILL_3": 30,
    "TITANIUM_FUEL_TANK": 90000,
    "BEACON_5": 180000,
    "TITANIUM_RELIC": 259200,
    "GOBLIN_OMELETTE_SPICY": 72000,
    "GEMSTONE_CHAMBER": 14400,
    "GEMSTONE_DRILL_3": 30,
    "RUBY_POLISHED_DRILL_ENGINE": 72000,
    "GEMSTONE_FUEL_TANK": 108000,
    //HOTM6
    "GOBLIN_OMELETTE_SUNNY_SIDE": 72000,
    "GOBLIN_OMELETTE_BLUE_CHEESE": 72000,
    "TITANIUM_DRILL_4": 30,
    "GEMSTONE_DRILL_4": 30,
    "SAPPHIRE_POLISHED_DRILL_ENGINE": 72000,
    "AMBER_MATERIAL": 25200,
    "DIVAN_HELMET": 82800,
    "DIVAN_CHESTPLATE": 82800,
    "DIVAN_LEGGINGS": 82800,
    "DIVAN_BOOTS": 82800,
    //HOTM7
    "AMBER_POLISHED_DRILL_ENGINE": 180000,
    "PERFECTLY_CUT_FUEL_TANK": 180000,
    "DIVAN_DRILL": 216000,
    "BASE_CAMP_TRAVEL_SCROLL": 36000,
    "SECRET_RAILROAD_PASS": 30,
    //HOTM8
    "GLACITE_AMALGAMATION": 14400,
    "REFINED_UMBER": 3600,
    "REFINED_TUNGSTEN": 3600,
    "UMBER_PLATE": 10800,
    "TUNGSTEN_PLATE": 10800,
    "UMBER_KEY": 1800,
    "TUNGSTEN_KEY": 1800,
    "REINFORCED_CHISEL": 43200,
    "DWARVEN_METAL": 86400,
    "PORTABLE_CAMPFIRE": 1800,
    "TUNGSTEN_KEYCHAIN": 21600,
    "DWARVEN_HANDWARMERS": 14400,
    //HOTM9
    "GLACITE_CHISEL": 64800,
    //HOTM10
    "PERFECT_CHISEL": 86400,
    //guessed
    "DIVAN_PENDANT": 604800,
    "PERFECT_PLATE": 21600,
    "SKELETON_KEY": 1800,
    "POWER_RELIC": 28800,
    "FRIGID_HUSK": 36000,
    //Pets
    //These are guesses until i can get the actual ID
    "MOLE": 259200,
    "TYRANNOSAURUS": 604800,
    "SPINOSAURUS": 604800,
    "GOBLIN": 604800,
    "ANKYLOSAURUS": 604800,
    "PENGUIN": 604800,
    "MAMMOTH": 604800,
  }
  var quickforgetimes = {
    0: 1,
    1: 0.895,
    2: 0.89,
    3: 0.885,
    4: 0.88,
    5: 0.875,
    6: 0.87,
    7: 0.865,
    8: 0.86,
    9: 0.855,
    10: 0.85,
    11: 0.845,
    12: 0.84,
    13: 0.835,
    14: 0.83,
    15: 0.825,
    16: 0.82,
    17: 0.815,
    18: 0.81,
    19: 0.805,
    //WHY DOES IT WORK LIKE THIS????? I DON'T FUCKING KNOW
    20: 0.7,
  }

  
var weights_vanguard = {
  shattered_locket: 3,
  skeleton_key: 6,
  umber_plate: 50,
  tungsten_plate: 50,
  mithril_plate: 30,
  glacite_amalgamation_2: 80,
  glacite_amalgamation_4: 40,
  refined_umber_2: 80,
  refined_tungsten_2: 80,
  blue_egg_1: 140,
  blue_egg_2: 70,
  book_ice_cold: 150,
  umber_key_1: 100,
  umber_key_2: 50,
  umber_key_4: 10,
  tungsten_key_1: 100,
  tungsten_key_2: 50,
  tungsten_key_4: 10,
  fl_onyx: 80,
  fl_peridot: 80,
  fl_citrine: 80, 
  fl_aquamarine: 80,
  f_onyx: 40,
  f_peridot: 40,
  f_citrine: 40,
  f_aquamarine: 40,
  suspicious_scrap_4: 150,
  refined_mithril_2: 60,
  refined_titanium_2: 60,
  bejeweled_handle_4: 150,
  jasper_crystal: 50,
  ruby_crystal: 50,
  opal_crystal: 50,
  aquamarine_crystal: 50,
  peridot_crystal: 50,
  onyx_crystal: 50,
  citrine_crystal: 50,
}
var translations_vanguard = {
  shattered_locket: "Shattered Locket",
  skeleton_key: "Skeleton Key",
  mithril_plate: "Mithril Plate",
  umber_plate: "Umber Plate",
  tungsten_plate: "Tungsten Plate",
  glacite_amalgamation_2: "Glacite Amalgamation ×2",
  glacite_amalgamation_4: "Glacite Amalgamation x4",
  refined_umber_2: "Refined Umber ×2",
  refined_tungsten_2: "Refined Tungsten ×2",
  blue_egg_1: "Blue Goblin Egg ×1",
  blue_egg_2: "Blue Goblin Egg ×2",
  book_ice_cold: "Enchanted Book (Ice Cold I)",
  umber_key_1: "Umber Key ×1",
  umber_key_2: "Umber Key ×2",
  umber_key_4: "Umber Key ×4",
  tungsten_key_1: "Tungsten Key ×1",
  tungsten_key_2: "Tungsten Key ×2",
  tungsten_key_4: "Tungsten Key ×4",
  fl_onyx: "Flawless Onyx Gem",
  fl_peridot: "Flawless Peridot Gem",
  fl_citrine: "Flawless Citrine Gem", 
  fl_aquamarine: "Flawless Aquamarine Gem",
  f_onyx: "Fine Onyx Gem ×160",
  f_peridot: "Fine Peridot Gem ×160",
  f_citrine: "Fine Citrine Gem ×160",
  f_aquamarine: "Fine Aquamarine Gem ×160",
  suspicious_scrap_4: "Suspicious Scrap ×4",
  refined_mithril_2: "Refined Mithril ×2",
  refined_titanium_2: "Refined Titanium ×2",
  bejeweled_handle_4: "Bejeweled Handle ×4",
  jasper_crystal: "Jasper Crystal",
  ruby_crystal: "Ruby Crystal",
  opal_crystal: "Opal Crystal",
  aquamarine_crystal: "Aquamarine Crystal",
  peridot_crystal: "Peridot Crystal",
  onyx_crystal: "Onyx Crystal",
  citrine_crystal: "Citrine Crystal",
}

var weights_metal = {
  umber_plate: 25,
  tungsten_plate: 25,
  umber_key: 10,
  tungsten_key: 10,
  glacite_amalgamation: 80,
  refined_umber: 80,
  refined_tungsten: 80,
  refined_mithril: 60,
  refined_titanium: 60,
  blue_egg: 100, 
  bejeweled_handle: 175,
  glacite_jewel_2: 250,
  book_ice_cold: 150,
  suspicious_scrap: 250,
  f_onyx_2: 800,
  f_onyx_4: 600,
  f_onyx_6: 400,
  f_onyx_8: 200,
  fl_onyx: 10,
  f_peridot_2: 800,
  f_peridot_4: 600,
  f_peridot_6: 400,
  f_peridot_8: 200,
  fl_peridot: 10,
  f_citrine_2: 800,
  f_citrine_4: 600,
  f_citrine_6: 400,
  f_citrine_8: 200,
  fl_citrine: 10,
  f_aquamarine_2: 800,
  f_aquamarine_4: 600,
  f_aquamarine_6: 400,
  f_aquamarine_8: 200,
  fl_aquamarine: 10,
  jasper_crystal: 50,
  ruby_crystal: 50,
  opal_crystal: 50,
  aquamarine_crystal: 50,
  peridot_crystal: 50,
  onyx_crystal: 50,
  citrine_crystal: 50,
}
  
var translations_metal = {
  umber_plate: "Umber Plate",
  tungsten_plate: "Tungsten Plate",
  umber_key: "Umber Key",
  tungsten_key: "Tungsten Key",
  glacite_amalgamation: "Glacite Amalgamation",
  refined_umber: "Refined Umber",
  refined_tungsten: "Refined Tungsten",
  refined_mithril: "Refined Mithril",
  refined_titanium: "Refined Titanium",
  blue_egg: "Blue Goblin Egg", 
  bejeweled_handle: "Bejeweled Handle",
  glacite_jewel_2: "Glacite Jewel ×2",
  book_ice_cold: "Enchanted Book (Ice Cold I)",
  suspicious_scrap: "Suspicious Scrap",
  f_onyx_2: "Fine Onyx Gem ×2",
  f_onyx_4: "Fine Onyx Gem ×4",
  f_onyx_6: "Fine Onyx Gem ×6",
  f_onyx_8: "Fine Onyx Gem ×8",
  fl_onyx: "Flawless Onyx Gem",
  f_peridot_2: "Fine Peridot Gem ×2",
  f_peridot_4: "Fine Peridot Gem ×4",
  f_peridot_6: "Fine Peridot Gem ×6",
  f_peridot_8: "Fine Peridot Gem ×8",
  fl_peridot: "Flawless Peridot Gem",
  f_citrine_2: "Fine Citrine Gem ×2",
  f_citrine_4: "Fine Citrine Gem ×4",
  f_citrine_6: "Fine Citrine Gem ×6",
  f_citrine_8: "Fine Citrine Gem ×8",
  fl_citrine: "Flawless Citrine Gem",
  f_aquamarine_2: "Fine Aquamarine Gem ×2",
  f_aquamarine_4: "Fine Aquamarine Gem ×4",
  f_aquamarine_6: "Fine Aquamarine Gem ×6",
  f_aquamarine_8: "Fine Aquamarine Gem ×8",
  fl_aquamarine: "Flawless Aquamarine Gem",
  jasper_crystal: "Jasper Crystal",
  ruby_crystal: "Ruby Crystal",
  opal_crystal: "Opal Crystal",
  aquamarine_crystal: "Aquamarine Crystal",
  peridot_crystal: "Peridot Crystal",
  onyx_crystal: "Onyx Crystal",
  citrine_crystal: "Citrine Crystal",
}
  
  